simpleBoard/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import RedirectView

from board.views import board_home, board_write, board_view, board_delete, board_edit, reply_write, reply_update, reply_delete 
from account.views import account_login, account_logout, account_add, account_update, account_delete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^$', board_home, name='no'),
    
    url(r'^write/', board_write, name='board_write'),
    url(r'^edit/(?P<board_id>\d+)/', board_edit, name='board_edit'),
    url(r'^view/(?P<board_id>\d+)/', board_view, name='board_view'),
    url(r'^delete/(?P<board_id>\d+)/', board_delete, name='board_delete'),

    url(r'^account/login', account_login, name='login'),
    url(r'^account/logout', account_logout, name='logout'),
    url(r'^account/create', account_add, name='account_add'),
    url(r'^account/update', account_update, name='account_update'),
    url(r'^account/delete', account_delete, name='account_delete'),

    url(r'^reply/write/(?P<board_id>\d+)/', reply_write, name='reply_write'),
    url(r'^reply/update/(?P<board_id>\d+)/(?P<reply_id>\d+)/', reply_update, name='reply_update'),
    url(r'^reply/delete/(?P<board_id>\d+)/(?P<reply_id>\d+)/', reply_delete, name='reply_delete'),
    
    url(r'^', board_home, name='board_home'),
]

board/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth import hashers
from itertools import chain
# Create your models here.
class Board(models.Model):
    id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50, blank=False)
    name = models.CharField(max_length=50, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    contents = models.TextField(blank=False)
    hits = models.IntegerField(default=0, blank=False)

    def get_absolute_url(self):
        return reverse('board_view', kwargs={"board_id":self.id})

    def get_replys(self):
        # reply_withchild = Reply.objects.none()
        reply_withchild = []
        depth = 0
        replys = Reply.objects.filter(board=self, depth=depth)
        depth += 1
        for reply in replys:
            # reply_withchild = chain(reply_withchild, reply, reply.get_reply_child(self))
            reply_withchild.append(reply)
            reply_withchild.extend(list(reply.get_reply_child(self)))
            # print(reply_withchild)
            # chain(reply_withchild, )
        return reply_withchild

    def get_replys_count(self):
        return Reply.objects.filter(board_id=self.id).count()

class Reply(models.Model):
    id = models.AutoField(primary_key=True)
    board = models.ForeignKey(Board, default=None)
    parent = models.ForeignKey("self", default=None, null=True, blank=True)
    depth = models.PositiveSmallIntegerField(default=0)
    comment = models.TextField(blank=False)
    name = models.TextField(blank=False)
    password = models.CharField(max_length=256)
    ipaddress = models.CharField(max_length=20, blank=False)
    created_date = models.DateTimeField(auto_now_add=True)
    
    def save(self):
        self.password = hashers.make_password(self.password)
        # print("save", self.password)
        return super().save()

    def get_reply_child(self, board):
        # child = Reply.objects.none()
        child = []
        replys = Reply.objects.filter(board=board, parent=self)
        for reply in replys:
            child.append(reply)
            child.extend(list(reply.get_reply_child(board)))
            # child = chain(child, reply, reply.get_reply_child(board))
            # chain(child, )
        return child

    

board/forms.py
from django import forms
from board.models import Board, Reply

class BoardForm(forms.models.ModelForm):
    
    class Meta:
        model = Board 
        fields = ('id', 'subject','name','contents',)
        # attrs={novalidate:'novalidate'}
        widgets = {
            'subject': forms.fields.TextInput(attrs={
                'placeholder': '제목',
                'class': 'form-control input-sm',
            }),
            'name': forms.fields.TextInput(attrs={
                'placeholder': '이름',
                'class': 'form-control input-sm',
            }),
            'contents': forms.Textarea(attrs={
                'rows': 20,
                'placeholder': '글',
                'class': 'form-control',
            }),
        }


class ReplyForm(forms.models.ModelForm):
    class Meta:
        model = Reply
        fields = ('name', 'comment', 'password')
        widgets = {
            'name':forms.fields.TextInput(attrs={
                'placeholder':'이름',
                'class': 'form-control input-sm',
            }),
            'comment':forms.Textarea(attrs={
                'placeholder':'댓글',
                'class': 'form-control',
                'rows':3,
                'cols':90,
            }),
            'password':forms.PasswordInput(attrs={
                'placeholder': '비밀번호',
                'class': 'form-control input-sm',
            })
        }

    def save(self, for_board, ipaddress, parent, depth):
        self.instance.board = for_board
        self.instance.ipaddress = ipaddress
        self.instance.parent = parent
        self.instance.depth = depth
        return super().save()

board/views.py
from django.shortcuts import render_to_response, render, redirect, reverse
from django.utils import timezone
from board.models import Board, Reply
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse
from board.forms import BoardForm, ReplyForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import hashers

#===========================================================================================
# 페이지줄수
SIMPLEBOARD_TITLE = "인코방"
rowsPerPage = 25
# HELP
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def board_home(request):
    title=SIMPLEBOARD_TITLE
    # if searchStr == None:
    error = request.GET.get('error','')
    searchStr = request.GET.get('searchStr','')
    page = request.GET.get('page',1)
       
    # if request.path == '/':
        # return redirect('/board/')

    if searchStr:
        # print ("searchStr", searchStr)
        boardList = Board.objects.filter(subject__contains = searchStr).order_by('-id')
    else:
        searchStr = ''
        boardList = Board.objects.order_by('-id')
            
    paginator = Paginator(boardList, rowsPerPage)
    
    try:
        boards = paginator.page(page)
    except PageNotAnInteger:
        boards = paginator.page(1)
    except EmptyPage:
        boards = paginator.page(paginator.num_pages)
    return render(request, 'lists.html', {'user':request.user,'page':page, 'boards': boards, 'searchStr':searchStr, 'title':title})

#===========================================================================================
def board_write(request):
    title=SIMPLEBOARD_TITLE+" - 글쓰기"
    error = request.GET.get('error','')
    if not request.user.is_authenticated():
        return redirect('board_home')
    page = request.GET.get('page',1)
    searchStr = request.GET.get('searchStr','')
    
    # if request.POST:
    #     print("POST", request.POST.get('id'))
    form = BoardForm(request.POST or None)
        # board = Board.objects.get(id=request.GET.get('board_id'))
        # form = BoardForm(instance=board)
    
    if form.is_valid():
        board_ = form.save()
        return redirect(reverse('board_view', kwargs={"board_id":board_.id})+'?page='+page+'&searchStr='+searchStr)
    return render(request, 'writeBoard.html', {"form": form, 'page':page, 'searchStr':searchStr, 'title':title})

def board_edit(request, board_id):
    title=SIMPLEBOARD_TITLE + " - 수정하기"
    if not request.user.is_authenticated():
        return redirect('board_home')
    page = request.GET.get('page',1)
    searchStr = request.GET.get('searchStr','')
    
    if request.POST:
        board = Board.objects.get(id=board_id)
        form = BoardForm(request.POST, instance=board)
    else:
        board = Board.objects.get(id=board_id)
        form = BoardForm(instance=board)
    
    if form.is_valid():
        board_ = form.save()
        return redirect(reverse('board_view', kwargs={'board_id':board_.id})+'?page='+page+'&searchStr='+searchStr)
    return render(request, 'editBoard.html', {"form": form, "board_id": board_id, 'page':page, 'searchStr':searchStr, 'title':title})

def board_delete(request, board_id):
    error = request.GET.get('error','')
    if not request.user.is_authenticated():
        return redirect('board_home')
    page = request.GET.get('page',0)
    searchStr = request.GET.get('searchStr','')
    board_ = Board.objects.get(id=board_id)
    board_.delete()
    # return redirect('board', page=page, searchStr=searchStr)
    return redirect(reverse('board_home')+'?page='+page+'&searchStr='+searchStr)

def board_view(request, board_id):
    title=SIMPLEBOARD_TITLE
    page = request.GET.get('page',0)
    searchStr = request.GET.get('searchStr','')
    board_ = Board.objects.get(id=board_id)
    title = title + " - " + board_.subject 
    error = request.GET.get('error','')
    board_.hits+=1
    board_.save()
    reply_form = ReplyForm()
    replys = board_.get_replys()
    boardList = None;
    if searchStr:
        # print ("searchStr", searchStr)
        boardList = Board.objects.filter(subject__contains = searchStr).order_by('-id')
    else:
        searchStr = ''
        boardList = Board.objects.order_by('-id')

    paginator = Paginator(boardList, rowsPerPage)
    
    try:
        boards = paginator.page(page)
    except PageNotAnInteger:
        boards = paginator.page(1)
    except EmptyPage:
        boards = paginator.page(paginator.num_pages)
    # return render(request, 'lists.html', {'user':request.user,'boards': boards, 'searchStr':searchStr})


    return render(request, 'viewBoard.html', {'reply_form':reply_form, 'boards': boards,  'board':board_, 'page':page, 'searchStr':searchStr, 'replys':replys, 'error':error, 'title':title})


def reply_write(request, board_id):
    page = request.GET.get('page',0)
    searchStr = request.GET.get('searchStr','')
    parent_id=request.GET.get('parent', None)
    parent = None
    if parent_id is not None:
        parent = Reply.objects.get(id=parent_id)
    depth = request.GET.get('depth', 0)
    ipaddress = get_client_ip(request)
    
    form = ReplyForm(request.POST)
    if form.is_valid():
        board = Board.objects.get(id=board_id)    
        reply = form.save(for_board=board, ipaddress=ipaddress, parent=parent, depth=depth)
        # print ("reply write!!!")
    return redirect(reverse('board_view', kwargs={'board_id':board_id})+'?page='+page+'&searchStr='+searchStr)

def reply_update(request, board_id, reply_id):
    page = request.GET.get('page',0)
    searchStr = request.GET.get('searchStr','')

    comment = request.POST.get('comment')
    password = request.POST.get('password')

    ipaddress = get_client_ip(request)
    reply = Reply.objects.get(id=reply_id)
    # print (hashers.make_password(password), reply.password)
    
    if not hashers.check_password(password, reply.password):
        error = '비밀번호가 다릅니다.'
        # return HttpResponse(formerror);
    else:
        reply.comment = comment
        reply.save()    
    
    # print ("reply update!!!")
    # return board_view(request, board_id)
    return redirect(reverse('board_view', kwargs={'board_id':board_id})+'?page='+page+'&searchStr='+searchStr+'&error='+error)

def reply_delete(request, board_id, reply_id):
    error = ""
    page = request.GET.get('page',0)
    searchStr = request.GET.get('searchStr','')
    reply = Reply.objects.get(id=reply_id)
    # print(reply.password)
    if reply is not None:
        if not hashers.check_password(request.POST.get("replyPassword"), reply.password):
            error = '비밀번호가 다릅니다.'
            # return HttpResponse(formerror);
        else:
            reply.delete()
    else:
        error = "해당항목이 없습니다." 

    return redirect(reverse('board_view', kwargs={'board_id':board_id})+'?page='+page+'&searchStr='+searchStr+'&error='+error)

board/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="/static/underscore.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="/static/board.js"></script>
    <link rel="stylesheet" href="/static/board.css">
    <title>{{title}}</title>
</head>
<body>
    <div class="left-bar">
        <!--left banner-->
    </div>
    <div class="header-bar"></div>
    <div class="contents">
        <div id="replyerrormsg" class="alert alert-danger" role="alert" style="display:none;">{{ error }}</div>
        {% block contents %}{% endblock %}
    </div>
    <div class="right-bar">
        <!--right banner-->
    </div>
</body>
</html>

board/templates/editBoard.html
{% extends 'base.html' %}
{% block contents %}
<script src="/static/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({ selector:'textarea',
        max_width:"100%",
        max_height:700,
        plugins: "media, image",
        toolbar: "media, image",
        media_live_embeds: true,
    });
</script>
<form class="form-horizontal" method='POST' action="{% url 'board_edit' board_id %}?page={{page}}&searchStr={{ searchStr }}" novalidate>
    
    {% csrf_token %}
    <div>
        {{ form.id }}
    </div>
    <div class="form-group">
        <div>
            {{ form.subject }}
        </div>
    </div>
    <div class="form-group">
        <div>
            {{ form.contents }}
        </div>
    </div>
    <hr>
    <div>
        <button class="btn btn-default btn-sm" type="submit">작성</button>
        <button class="btn btn-default btn-sm" type="button" onclick="location.href='{% url 'board_home' %}?page={{page}}&searchStr={{ searchStr }}'">뒤로</button>
    </div>
</form>

{% endblock %}

board/templates/list_template.html
{% load arithmetic %}
<table class=table>
    <tr class="small text-center">
        <td class="col-sm-1 center">번호</td>
        <td class="col-sm-8">제목</td>
        <td class="col-sm-3 center">등록일</td>
    </tr>
    {% if boards %}
        {% for boardRow in boards %}     
        <tr class="small text-center">
            <td>{{ boardRow.id }}</td>
            <td class="text-left">
                <a href="{% url 'board_view' boardRow.id %}?page={{page}}&searchStr={{searchStr}}">{{ boardRow.subject }}</a> [{{boardRow.get_replys_count}}]
                {% if boardRow.created_date|new %} <img src="/static/img/new.gif"/> {% endif %}
            </td>
            <td>{{ boardRow.created_date|date:"Y-m-d H:i:s" }}</td>
        </tr>       
        {% endfor %}
    {% else %}
        <p>No Data.</p>
    {% endif %}
</table>
<!--pagination start-->

<div class="text-center">
    <ul class="pagination">
        <li>
            <a href="{% url 'board_home' %}?page={{page}}&searchStr={{searchStr}}" {% if not boards.page.has_previous %}disabled{% endif %}>&laquo;</a>
        </li>
        {% with active_page=boards.number %}
        {% for page_number in boards.paginator.page_range %}
            {% if boards.number > 5 and page_number < boards.number|sub:4 %}
            {% elif boards.number > 5 and page_number == boards.number|sub:4 %}
            {% elif boards.number < boards.paginator.num_pages|sub:5 and page_number > boards.number|add:4 %}
            {% elif boards.number < boards.paginator.num_pages|sub:5 and page_number == boards.number|add:4 %}
            {% else %}
                <li {% if page_number == boards.number %}class="active"{% endif %} foo="3">
                    <a href="{% url 'board_home' %}?page={{page_number}}&searchStr={{searchStr}}">{{ page_number }}</a>
                </li>
            {% endif %}             
        {% endfor %}
        {% endwith %}
        <li>
            <a href="{% url 'board_home' %}?page={{boards.paginator.num_pages}}&searchStr={{searchStr}}" {% if not boards.page.has_previous %}disabled{% endif %}>&raquo;</a>
        </li>
    </ul>
</div>
<!--pagination end-->

<form method='GET'>
<div class="input-group">
    <input class="form-control input-sm" placeholder="글찾기" type=text name=searchStr action="{% url 'board_home' %}" value={{searchStr}}>
    <span class="input-group-btn">
        <button class="btn btn-default btn-sm" type="submit">글찾기</button>
    </span>    
</div>
</form>

board/templates/lists.html
{% extends 'base.html' %}
{% block contents %}

{% if user.is_authenticated %}
    USER: {{ user.username }} 
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'logout' %}'">Logout</button>
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'board_write' %}'">글쓰기</button>
{% endif %}
<div class="contents-banner">
    <!--banner-->
</div>
<div class="boardlist">
    {% include 'list_template.html' %}
</div>
<div class="bottom-bar">
    <!--bottom banner-->
</div>
{% endblock %}

board/templates/replyInput.html
<div class="container">
<form class="form-inline" method='POST' action="{% url 'reply_write' board_id=board.id %}?page={{page}}&searchStr={{searchStr}}" novalidate>
    {% csrf_token %}
    <div class="form-group row">
        {{ reply_form.comment }}
    </div>
    <div class="row">
        <div class="form-group">
            {{ reply_form.name }}
        </div>
        <div class="form-group">
            {{ reply_form.password }}
        </div>
        <button class="btn btn-default btn-sm" type="submit">입력</button>
    </div>
</form>
</div>
<hr>

board/templates/replylist.html
{% load arithmetic %}

<script>
$(document).ready(function() {
    var replyInputCnt = 0;
    $(document).on("click", ".glyphicon-trash", function () {
        $("#modalinputpassword").val("");
        $("#modalinputpassword").focus();
        var replyid = $(this).data('id');
        //  console.log(replyid);
        var urlstring = "/reply/delete/{{ board.id }}/"+replyid+"/?&page={{page}}&searchStr={{searchStr}}";
        $("#modalpassword").attr({action:urlstring});
        
    }).on("click", ".glyphicon-comment", function(){
        if(replyInputCnt==0){
            var parent = $(this).data('id');
            var depth = $(this).data('depth');
            depth++;
            var urlstring = "{% url 'reply_write' board_id=board.id %}?parent="+parent+"&depth="+depth+"&page={{page}}&searchStr={{searchStr}}";
            var tmplMarkup = $('#replyinputtmp').html();
            // console.log(tmplMarkup)
            var compiledTmpl = _.template(tmplMarkup);

            $(this).parent().after(compiledTmpl({actionurl:urlstring}));
            replyInputCnt++;
        }
    }).on("click", ".glyphicon-pencil", function(){
        if(replyInputCnt==0){
            var id = $(this).data('id');
            var depth = $(this).data('depth');
            var comment = $(this).data('comment');
            // console.log(comment);
            depth++;
            var urlstring="/reply/update/{{ board.id }}/"+id+"/?&page={{page}}&searchStr={{searchStr}}";
            var tmplMarkup = $('#replyedittmp').html();
            
            var compiledTmpl = _.template(tmplMarkup);

            $(this).parent().next().append(compiledTmpl({comment:comment, actionurl:urlstring}));
            $("#comment"+id).hide();
            replyInputCnt++;
        }else{
            
        }
    }).on("click", "#close_edit_reply", function(){
        // console.log($(this).html());
        $("span:hidden").show();
        $("div").remove("#editreply");
        replyInputCnt--;
    }).on("click", "#close_add_reply", function(){
        $("div").remove("#addreply");
        replyInputCnt--;
    });
});


</script>

{% for reply in replys %}
    <ul class="">
        <div class="comment" style="padding-left:{{16|mul:reply.depth}}px;">
            {% if reply.depth > 0 %}
                <i class="fa fa-share fa-flip-vertical repicon"></i>            
            {% endif %}
            <b>{{ reply.name }}</b> &nbsp;&nbsp;{{reply.created_date|date:"Y-m-d H:i:s"}} &nbsp;&nbsp; ({{ reply.ipaddress|ip }}) &nbsp;&nbsp;
            <span class="text-right comment-tool">
                <button class="btn btn-default btn-sm glyphicon glyphicon-pencil" aria-hidden="true" data-comment="{{ reply.comment }}" data-id="{{ reply.id }}"></button>
                <button class="btn btn-default btn-sm glyphicon glyphicon-trash" aria-hidden="true" data-toggle="modal" data-target="#myModal" data-id="{{ reply.id }}"></button>
                <button class="btn btn-default btn-sm glyphicon glyphicon-comment" aria-hidden="true" data-depth="{{ reply.depth }}" data-id="{{ reply.id }}"></button>
            </span>
            <div class="comment-text">
                <span id="comment{{reply.id}}">{% autoescape off %} {{ reply.comment|linebreaks }} {% endautoescape %}</span>
            </div>
        </div>
    </ul>
    <hr>
{% endfor %}

<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog">
        <form id="modalpassword" method="POST" action="">
            {% csrf_token %}
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">삭제하려면 비밀번호를 입력하세요.</h4>
            </div>
            <div class="modal-body">
            <input id="modalinputpassword" type="password" name="replyPassword">
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-default btn-sm">확인</button>
                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">취소</button>
            </div>
        </div>
        </form>
    </div>
</div>

<script type="text/template" id="replyinputtmp">
    <div class="container" id = addreply>
    <form class="form-inline" method='POST' action= <%= actionurl %> novalidate>
        {% csrf_token %}
        <div class="form-group row">
            {{ reply_form.comment }}
        </div>
        <div class="row">
            <div class="form-group">
                {{ reply_form.name }}
            </div>
            <div class="form-group">
                {{ reply_form.password }}
            </div>
            <button class="btn btn-default btn-sm" type="submit">입력</button>
            <button id="close_add_reply" class="btn btn-default btn-sm" type="button">닫기</button>
        </div>
    </form>
    </div>
</script>

<script type="text/template" id="replyedittmp">
    <div class="container" id="editreply">
    <form id="replyedit" class="form-inline" method='POST' action= <%= actionurl %> novalidate>
        {% csrf_token %}
        <div class="form-group row">
            <textarea class="form-control" cols="90" id="id_comment" name="comment" placeholder="댓글" rows="3" required=""><%= comment %></textarea>
        </div>
        <div class="row">
            <div class="form-group">
                {{ reply_form.password }}
            </div>
            <button class="btn btn-default btn-sm" type="submit">입력</button>
            <button id="close_edit_reply" class="btn btn-default btn-sm" type="button">닫기</button>
        </div>
    </form>
    </div>
</script>

board/templates/viewBoard.html
{% extends 'base.html' %}
{% block title %}글보기{% endblock %}
{% block contents %}
{% if user.is_authenticated %}
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'board_write' %}'">글쓰기</button>
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'board_edit' board_id=board.id %}?page={{page}}&searchStr={{searchStr}}&board_id={{board.id}}'">수정</button>    
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'board_delete' board_id=board.id %}?page={{page}}&searchStr={{searchStr}}'">삭제</button>
{% endif %}


<div>
    <hr>
    <div class="row">
        <div class="col-sm-9"><b>{{board.subject}}</b></div>
        <div class="col-sm-3 text-right">{{ board.created_date|date:"Y-m-d H:i:s" }}</p></div>
    </div>
    <hr>
    <div class="contents-banner">
        <!--banner-->
    </div>


    <div class="panel panel-default">
        <div class="panel-body">
            {% autoescape off %}
            {{ board.contents }}
            {% endautoescape %}    
        </div>
    </div>
</div>
<hr>
<div class="contents-banner">
    <!--banner-->
</div>

<div class="text-right">
    <button class="btn btn-default btn-sm" onclick="location.href='{% url 'board_home' %}?page={{page}}&searchStr={{searchStr}}'">글목록</button>
</div>

<hr>
<div class="replylist">
{% if replys is not None %}
{% include 'replylist.html' %}
{% endif %}
</div>
<div class="replyinput">
{% include 'replyInput.html' %}
</div>
<div class="contents-banner">
    <!--banner-->
</div>
{% include 'list_template.html' %}
<div class="contents-banner">
    <!--banner-->
</div>
{% endblock %}

board/templates/writeBoard.html
{% extends 'base.html' %}
{% block contents %}
<script src="/static/tinymce/tinymce.min.js"></script>
<script>
    tinymce.init({ selector:'textarea',
        max_width:"100%",
        max_height:700,
        plugins: "media, image",
        toolbar: "media, image",
        media_live_embeds: true,
    });
</script>
<form class="form-horizontal" method='POST' action="{% url 'board_write' %}?page={{page}}&searchStr={{ searchStr }}" novalidate>
    
    {% csrf_token %}
    <div>
        {{ form.id }}
    </div>
    <div class="form-group">
        <div>
            {{ form.subject }}
        </div>
    </div>
    
    <div class="form-group">
        <div>
            {{ form.contents }}
        </div>
    </div>
    <hr>
    <div>
        <button class="btn btn-default" type="submit">작성</button>
        <button class="btn btn-default" type="button" onclick="location.href='{% url 'board_home' %}?page={{page}}&searchStr={{ searchStr }}'">뒤로</button>
    </div>
</form>

{% endblock %}